# Generated by Django 3.2.12 on 2022-04-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1)),
                ('stored_since', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'cheeses',
                'ordering': ['name'],
            },
        ),
    ]
